CONTIKI = ../..

CFLAGS+=-DPROJECT_CONF_H=\"project-conf.h\"

PROJECT_SOURCEFILES +=  tree_lib.c

CONTIKI_WITH_RIME = 1

#$(info MY_TX_POWER_DBM is ${MY_TX_POWER_DBM})
#CFLAGS += -DMY_TX_POWER_DBM=${MY_TX_POWER_DBM}

include $(CONTIKI)/Makefile.include
